name: Build Windows EXE

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  VERSION: 1.2

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET 10
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Publish Windows build
      run: |
        dotnet publish ./DRCFLCClient.csproj `
          -c Release `
          -r win-x64 `
          --self-contained true `
          /p:PublishSingleFile=true `
          -o publish

    - name: Create ZIP archive
      run: |
        Compress-Archive `
          -Path publish\DRCFLCClient.exe `
          -DestinationPath drcflcclient-${{ env.VERSION }}-win-x64.zip

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: drcflcclient-win-x64
        path: "*.zip"
